"use client"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Header from "./components/header"
import authService from "@/domain/services/auth.service"
import { useEffect, useState } from "react"
import LoadingPage from "./loading/page"
import useSessionState from "./hooks/sessionState"
import Session from "@/domain/models/session.model"
import SessionContext from "./context/session.context"
import Home from "./page"
import { useRouter } from "next/navigation"

const inter = Inter({ subsets: ["latin"] })

// export const metadata: Metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// }

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	const [isLoading, setIsLoading] = useState<boolean>(true)
	const { sessionState, setSessionState } = useSessionState()

	const router = useRouter()

	useEffect(() => {
		authService.onSessionChange((session: Session | null) => {
			setSessionState(session)
			setIsLoading(false)
		})

		authService.onSignOut(() => {
			setIsLoading(false)
			setSessionState(null)
			router.push("/")
		})
	}, [])
	return (
		<SessionContext.Provider value={sessionState}>
			<html lang="en">
				<body className={inter.className}>
					{isLoading ? (
						<LoadingPage />
					) : (
						<>
							<Header />
							{children}
						</>
					)}
				</body>
			</html>
		</SessionContext.Provider>
	)
}
